# Generated by Django 5.2.6 on 2025-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое название задачи(до 255 символов)', max_length=255, verbose_name='Название задачи')),
                ('status', models.CharField(choices=[('created', 'Созданно'), ('in_progres', 'В работе'), ('completed', 'Завершено')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Времяб когда задача', verbose_name='Дата создание')),
            ],
        ),
    ]
